# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a5e5d2b845e96a5c9de6daf0f06438bd8a8718740f703164c337d59304ceadf259accdb52677f91d650771261ff615795c646e9ef311b8b8a01a949db6ada41

test:
  secret_key_base: a2325a10841c5b2d4682f74c982e18c3d6ca03a70244bc1d566ac5fcb0c3e3b2b0fa05ac6fe622802af7b5970b509fb297ee86b7e8156f89dc9e959d3137eeba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
